version: '3.8'

services:
  gitlab:
    build:
      context: .       # Le dossier actuel contient le Dockerfile
      dockerfile: Dockerfile  # Par défaut, il cherche un fichier nommé Dockerfile
    container_name: gitlab
    hostname: gitlab.vlne.lan
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.vlne.lan:9080';
        nginx['listen_port'] = 80;
        gitlab_rails['backup_path'] = '/var/opt/gitlab/backups';
        gitlab_rails['gitlab_data_dir'] = '/var/opt/gitlab';
        gitlab_rails['gitlab_log_dir'] = '/var/log/gitlab';
    ports:
      - "9080:80"    # HTTP
      - "9443:443"   # HTTPS
      - "2222:22"    # SSH
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    restart: always

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
